(function(root){'use strict';function mount({button,canEnter=()=>true,getFace=()=>0,resolveSpeech=s=>s,onEnter=()=>{},onLeave=()=>{}}){
 const M=root.FrogVillageWorld,$=s=>document.getElementById('village-'+s),section=document.getElementById('village'),canvas=$('canvas'),ctx=canvas.getContext('2d',{alpha:false}),room=document.getElementById('app');let world=M.create(),art=null,loading=null,active=false,raf=0,last=0,width=1,height=1,dpr=1,listeners=null,pointer=null,follow=true,overview=false,panUntil=0,pending=null,noticeUntil=0,previousFocus=null;const cam={x:610,y:697,zoom:1.3,debug:false},stats={enters:0,frames:0,starts:0,costs:[],blockedTaps:0};
 function speak(text,ms=2800){$('notice').textContent=text;$('notice').hidden=false;noticeUntil=performance.now()+ms;}
 function resize(){if(!active)return;const r=section.getBoundingClientRect();width=r.width;height=r.height;dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);cam.zoom=overview?Math.min((width-12)/M.W,(height-90)/M.H):width<650?1.3:Math.max(1.25,Math.min(1.8,width/820));clampCamera();}
 function view(){return{x:cam.x,y:cam.y,w:width/cam.zoom,h:height/cam.zoom};}
 function clampCamera(){const hw=width/cam.zoom/2,hh=height/cam.zoom/2;cam.x=hw>=M.W/2?M.W/2:M.clamp(cam.x,hw,M.W-hw);cam.y=hh>=M.H/2?M.H/2:M.clamp(cam.y,hh,M.H-hh);}
 function frame(ts){raf=0;if(!active||document.hidden||!art)return;const start=performance.now(),dt=last?Math.min(.07,(ts-last)/1000):0;last=ts;M.step(world,dt,view());world.player.face=getFace();
 if(pending&&!world.player.path.length&&!world.player.action){if(pending.kind==='zone'){if(M.enterAction(world,pending.id))speak(resolveSpeech(M.zones.find(z=>z.id===pending.id).line));else if(pending.id==='elephant'&&world.events.slide.active){if(!pending.waiting){speak('等前面的小宝滑完，就轮到小宝蛙。');pending.waiting=true;}pending.keep=true;}}else{const n=world.npcs.find(n=>n.id===pending.id);if(n&&Math.hypot(n.x-world.player.x,n.y-world.player.y)<65){n.path=[];n.reactUntil=world.t+5;n.cooldown=world.t+40;n.state='look';n.dir=world.player.x<n.x?-1:1;world.player.dir=n.x<world.player.x?-1:1;}}if(pending?.keep)pending.keep=false;else pending=null;}
 if(!overview&&!follow&&!pointer?.drag&&world.player.moving&&ts>panUntil)follow=true;
 if(!overview&&follow&&!pointer?.drag){const a=1-Math.exp(-dt*6);cam.x+=(world.player.x-cam.x)*a;cam.y+=(world.player.y-35/cam.zoom-cam.y)*a;clampCamera();}
 art.render(ctx,world,cam,width,height,dpr);if(!$('notice').hidden){if(performance.now()>noticeUntil)$('notice').hidden=true;else{const x=width/2+(world.player.x-cam.x)*cam.zoom,y=height/2+(world.player.y-cam.y-62)*cam.zoom;$('notice').style.left=M.clamp(x,100,width-100)+'px';$('notice').style.top=M.clamp(y,70,height-80)+'px';}}
 stats.frames++;if(stats.costs.length>=300)stats.costs.shift();stats.costs.push(performance.now()-start);raf=requestAnimationFrame(frame);
 }
 function start(){if(active&&!document.hidden&&art&&!raf){last=0;stats.starts++;raf=requestAnimationFrame(frame);}}
 function stop(){cancelAnimationFrame(raf);raf=0;last=0;pointer=null;}
 function screenPoint(e){const r=canvas.getBoundingClientRect();return{x:cam.x+(e.clientX-r.left-width/2)/cam.zoom,y:cam.y+(e.clientY-r.top-height/2)/cam.zoom};}
 function tap(p){if(world.player.action)return;follow=true;pending=null;const candidates=world.npcs.filter(n=>!n.hidden&&!['angel','bed','swimmer'].includes(n.role)&&!['slide','climb','craft-enter','craft-leave','sea-play'].includes(n.state)&&Math.hypot(p.x-n.x,p.y-(n.y-20))<Math.max(24,25/cam.zoom)).sort((a,b)=>Math.hypot(p.x-a.x,p.y-a.y)-Math.hypot(p.x-b.x,p.y-b.y));
 if(candidates.length){const n=candidates[0],dest=M.roadPoint({x:n.x+28,y:n.y+12});if(dest&&M.go(world,dest))pending={kind:'npc',id:n.id};return;}
 const hits={flowers:[134,470,70,57],orchard:[163,248,123,132],cow:[240,395,88,47],pig:[143,604,62,42],house:[598,350,114,93],bus:[907,425,114,70],fountain:[685,571,81,94],pool:[922,658,121,78],craft:[139,824,116,81],elephant:[684,861,118,106],toilet:[993,834,66,103],beach:[446,1217,140,89]};let hit=null;for(const[id,[x,y,rx,ry]]of Object.entries(hits))if(((p.x-x)/rx)**2+((p.y-y)/ry)**2<1){hit=id;break;}
 if(hit){const z=M.zones.find(z=>z.id===hit);if(M.go(world,{x:z.at[0],y:z.at[1]}))pending={kind:'zone',id:hit};return;}
 const dest=M.roadPoint(p);if(!dest||Math.hypot(dest.x-p.x,dest.y-p.y)>60||!M.go(world,dest)){stats.blockedTaps++;speak('这边过不去，沿着小路绕一绕。',1800);}
 }
 function toggleOverview(){overview=!overview;$('overview').textContent=overview?'◎ 跟随':'▧ 全村';$('overview').setAttribute('aria-pressed',String(overview));resize();cam.x=overview?M.W/2:world.player.x;cam.y=overview?M.H/2:world.player.y;follow=!overview;clampCamera();}
 function bind(){listeners=new AbortController();const signal=listeners.signal;canvas.addEventListener('pointerdown',e=>{if(e.button>0||pointer)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,drag:false};canvas.setPointerCapture(e.pointerId);e.preventDefault();},{signal});
 canvas.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>9)pointer.drag=true;if(pointer.drag&&!overview){follow=false;cam.x-=(e.clientX-pointer.lastX)/cam.zoom;cam.y-=(e.clientY-pointer.lastY)/cam.zoom;clampCamera();}pointer.lastX=e.clientX;pointer.lastY=e.clientY;},{signal});
 canvas.addEventListener('pointerup',e=>{if(!pointer||e.pointerId!==pointer.id)return;const drag=pointer.drag;pointer=null;if(drag)panUntil=performance.now()+1800;if(!drag)tap(screenPoint(e));},{signal});canvas.addEventListener('pointercancel',()=>{pointer=null;},{signal});canvas.addEventListener('lostpointercapture',()=>{pointer=null;},{signal});
 $('home').addEventListener('click',leave,{signal});$('overview').addEventListener('click',toggleOverview,{signal});window.addEventListener('resize',resize,{signal});window.visualViewport?.addEventListener('resize',resize,{signal});document.addEventListener('visibilitychange',()=>document.hidden?stop():start(),{signal});window.addEventListener('pagehide',stop,{signal});}
 async function enter(){if(active||!canEnter())return;active=true;stats.enters++;previousFocus=document.activeElement;onEnter();room.hidden=true;room.inert=true;section.hidden=false;document.body.classList.add('in-village');bind();resize();cam.x=overview?M.W/2:world.player.x;cam.y=overview?M.H/2:world.player.y;follow=!overview;clampCamera();$('home').focus();speak('小宝村的小路正在打开…',30000);try{if(!loading)loading=root.FrogVillageArt.load().then(root.FrogVillageArt.create).catch(e=>{loading=null;throw e;});art=await loading;if(!active)return;$('notice').hidden=true;start();}catch(e){console.error(e);if(active)speak('村庄素材没有加载完整，先回家再试一下。',60000);}}
 function leave(){if(!active)return;active=false;stop();listeners?.abort();listeners=null;pending=null;world.player.path=[];if(world.player.action){Object.assign(world.player,world.player.action.return,{action:null,lift:0,slideStage:null,water:false});if(world.events.slide.active?.id==='player')world.events.slide.active=null;}section.hidden=true;room.hidden=false;room.inert=false;document.body.classList.remove('in-village');onLeave();(previousFocus||button).focus();}
 button.addEventListener('click',enter);
 if(new URLSearchParams(location.search).has('villageTest'))root.__villageTest={get world(){return world;},enter,leave,tap,pan(x,y){follow=false;cam.x=x;cam.y=y;clampCamera();},warp(x,y){const p=M.nearest({x,y});if(p){Object.assign(world.player,p,{path:[],action:null,lift:0});cam.x=p.x;cam.y=p.y;follow=true;clampCamera();}},debug(value){cam.debug=value;},advance(sec){for(let t=0;t<sec;t+=.05)M.step(world,.05,view());},snapshot(){return{active,raf:!!raf,listeners:!!listeners,stats:{...stats,costs:[...stats.costs]},camera:{...cam,overview},player:{...world.player},events:JSON.parse(JSON.stringify(world.events)),time:world.t,metrics:{...world.metrics}};}};
 return{enter,leave,isActive:()=>active,reset(){if(!active){world=M.create();pending=null;}}};
}
root.FrogVillage={mount};})(globalThis);
